name: cm_fit
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - pip
  - conda-forge::pandas
  - conda-forge::scikit-learn
  - conda-forge::scikit-image
  - netcdf4
  - matplotlib
  - pytest
  - pip:
    - tensorflow-gpu>=2.3.0
